---
name: Dev Build and Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Repo environment
        required: true
        type: choice
        default: dev
        options:
          - dev
          - qa

run-name: Deploy ${{ github.ref_name }} to ${{ inputs.environment }} by @${{ github.actor }}

jobs:
  dev-deploy:
    uses: indurivarun/pipeline.actions/.github/workflows/lower-deploy.yaml@main
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    with:
      project-type: reactjs
      environment: ${{ inputs.environment }}
    secrets: inherit